### ISSUE TITLE
Collect photos for each team's events

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#11]
We need these from Marketing. They'll be stored under the each Team's photos property (see api docs).

**Comment by maxdumas** [comment]
@ethanresnick Please create the endpoint to upload photos to

**Comment by AbhiAgarwal** [comment]
@maxdumas 

I had some free-time today so I created this basic service: http://services.tnyu.org/simple-form
The idea is just to POST to ``http://services.tnyu.org/upload`` with the photo, and it'll then give you this back:

```
{
filePath: "http://services.tnyu.org/uploads/upload_1c914016b22d2c27c6e8be09fe7a7eca.jpg"
}
```

Which contains the filePath - the place where the image is uploaded. The form can be placed anywhere it just needs to POST. The code might have a couple bugs, but I'll try get those fixed on Saturday.

**Comment by ethanresnick** [comment]
@abhinayashutosh heads up!

**Comment by abhinayashutosh** [comment]
Thanks - Shared the images folder with you. All future images will go in there!

**Comment by ethanresnick** [comment]
@abhinayashutosh Thanks Abhi! Can you please put them in the shared Tech@NYU folder too, under the Marketing folder? That way, other people can use these pictures too. (I'd do it, but it doesn't look like I have permission to do so.) I'm looking forward to seeing this folder grow as you're able to collect photos from elsewhere, too! I want this to become a curated collection of consistently-styled, high-quality photos that we can just quickly drop into our marketing campaigns.

**Comment by abhinayashutosh** [comment]
Yep, just moved it. 

More pictures should be coming in shortly from others I've reached out to and from our upcoming events.
