### ISSUE TITLE
List SchoolAttendances by Id

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#113]
Listing `SchoolAttendance`s by name in the typeahead for `Person.schools` is just going to lead users to accidentally pick the wrong `SchoolAttendance`. That is, they'll be adding a Person that goes to NYU and they'll pick a `SchoolAttendance` originally created for a different NYU student, and that SchoolAttendance will have the wrong graduation date and major, messing up our data. 

This'll solve itself once we implement dependent resources but, until then, listing SchoolAttendances by id in the `Person.schools` typeahead, like we do with `TeamMemberships` is (counter-intuitively) better than listing them by name, since at least it means people won't pick the wrong SchoolAttendance.

**Comment by maxdumas** [comment]
Done, awaiting merge to master. Will batch into a larger PR before closing this.
