### ISSUE TITLE
Cannot add venue

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#125]
For some reason you cannot add a venue. @maxdumas. @jhishan found it. It doesn't let you add because it says the address is missing.

It's trying to POST this to the API. It seems to be missing `name` and `address`. I think there's some problem with TinyMCE (cc @ethanresnick).

``` json
{
    "data": {
        "attributes": {
            "notes": "",
            "category": "Company Office",
            "seats": 75
        },
        "links": {
            "organization": {
                "linkage": null
            }
        },
        "type": "venues"
    }
}
```

**Comment by ethanresnick** [comment]
@AbhiAgarwal when you make the POST manually, it works though, right? (Trying to figure out if it's an intranet issue or an API one.)

**Comment by ethanresnick** [comment]
Possibly related: #119. In which case the best advice **for now** might be to just refresh the page and re-enter the data. Fucking bugs.

**Comment by AbhiAgarwal** [comment]
Oh lol. I'll try it again. Thnx @ethanresnick. No idea why I never encountered this in the past.

**Comment by AbhiAgarwal** [comment]
It works when you manually enter the data. It is not an API issue.

Can someone look into this please? @maxdumas @ethanresnick. I am not being able to even add an organization and I've tried doing it on two different computers at least 2-3 times. Would really appreciate it! Currently having to add things for everyone manually.

**Comment by maxdumas** [comment]
@AbhiAgarwal Sorry man I literally have not been able, though it's definitely high priority. I've put @imAlan onto it for the time being. Hopefully I can find time this weekend.

**Comment by AbhiAgarwal** [comment]
NP @maxdumas. Don't worry about it right now then. Concentrate on your work!
