### ISSUE TITLE
Clicking Profile should go to /people/edit/me not people/edit/<id>

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#127]

**Comment by ethanresnick** [comment]
ref TechAtNYU/api#97

**Comment by AbhiAgarwal** [comment]
Yup! @ethanresnick I just opened this so I could make a feature branch. I submitted a PR here:

https://github.com/TechAtNYU/intranet/pull/128

**Comment by maxdumas** [comment]
Resolved by #128.
