### ISSUE TITLE
Populate liasons on `List Organization`

### ISSUE THREAD

**Issue by brentdur** [TechAtNYU/intranet#145]
The liasons field should populated with the people names (similar to how `member.name` was populated [Here](https://github.com/TechAtNYU/intranet/pull/144/files#diff-9fd8c5da54f7bdba6a08d0b41a6b06e5R29)  )

Also fix the direct loading problem (if you go to http://intranet.sexy/#/r//list/54404c98cfc7e4185756a586 (an example with liasons) it doesn't load at all. Should load + liasons). This was done [Here](https://github.com/TechAtNYU/intranet/pull/144/files#diff-78ffbd6f059672cc0bac94d099c149a4R54) last time

Boilerplated a branch: feature/145/main

**Comment by ashleytqy** [comment]
fixed ~
