### ISSUE TITLE
Collect Event Attendees

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#15]
For each event, read facebook's list of attendees back in, and store the list of attendees in the API's `event.attendees`. This will require creating a [Person object](https://api.tnyu.org/#resources-people) for each attendee we haven't seen before, and mapping the Facebook users to our API's Person objects for attendees we have seen before.

The best way to do this would probably be to add a `person.facebookId` property, paralleling the `person.twitterId` property we already have.

**Comment by AbhiAgarwal** [comment]
I'm working on this

**Comment by AbhiAgarwal** [comment]
moved to repo: https://github.com/TechAtNYU/event-signin
