### ISSUE TITLE
Fix Event List feature

### ISSUE THREAD

**Issue by brentdur** [TechAtNYU/intranet#151]
There are a lot of fields on events that aren't shown as they are linked id's (basically go to any event and look at all the empty fields). Let's populate those with actual information

Furthermore, for `Attendees` and `Rsvps` let's add augmented fields `Num of __` that do simple counts on the number of attendees and people rsvp'd. This will solve the current problem of counting. 

Lastly, changing the list dropdown to be split up by month (So it would have a header "May 2015" and then the events under it) or searchable by date as well as title (select two dates and show all events between) would be great features. Currently this uses [Angular Chosen](https://github.com/leocaseiro/angular-chosen) but if this doesn't provide the functionality you need you can of course use whatever library you want

**Comment by ashleytqy** [comment]
fixed.
