### ISSUE TITLE
Reorganizing home page

### ISSUE THREAD

**Issue by ashleytqy** [TechAtNYU/intranet#190]
Right now all the resources are listed in a grid. The idea is to make it easier for people to access the resources they use often (i.e. Events), and organise the resources into groups based on how frequently they are used.

Used often -> Events
Used occasionally -> Teams, Memberships, Positions, People, Organizations, Venues
Rarely used -> All the others not mentioned

Only a view level change.

**Comment by ashley** [comment]
Closed by #196
