### ISSUE TITLE
Fix Errors Regarding Angular Multipleselect

### ISSUE THREAD

**Issue by maxdumas** [TechAtNYU/intranet#32]
Whenever an entry is selected in the multiselects, the following error gets spit out:

TypeError: Cannot set property 'ticked' of undefined

It probably has something to do with the way our model is set up; removing the tick-property attribute from the tab didn't fix it.

**Comment by ethanresnick** [comment]
@maxdumas can this be closed?

**Comment by maxdumas** [comment]
Yep! Sure can. We're not even using these anymore.
