### ISSUE TITLE
Add event form: textareas should be HTML wsiwyg editors

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#50]
In the add event form, the `details` field should actually post HTML to the API, not plain text, as it's pretty common that the user will want to add HTML in this field, e.g. for hyperlinks, bullets, etc.

Now, we could let the user write markdown in the textarea (and somehow communicate that this is allowed), and then convert the markdown to html before posting. But, I think it'd be more user-friendly to just apply [Redactor](http://imperavi.com/redactor/) or similar to these textareas. That'll generate the HTML for the user.

**Comment by irisyuan** [comment]
Do we already have a paid Redactor license? They're willing to give us a Basic for free if we link to them at the bottom of the page.

**Comment by ethanresnick** [comment]
Ahh, I didn't realize Redactor costs money. This doesn't seem like something we need to pay for. I [customized TinyMCE](http://www.ethanresnick.com/misc/hp/blogger/post.php) a couple years back to strip out all the cruft and, if we updated the icons (they're ugly and pre-retina), I think it could do everything we need. 

Of course, there's also the free [Medium editor](https://github.com/daviferreira/medium-editor). Its main UX difference is that it only shows the toolbar when text is selected, which makes the UI less obtrusive but also less discoverable—a tradeoff that may or may not be right for our intranet.

**Comment by AbhiAgarwal** [comment]
@ethanresnick Just an FYI, but I found that the medium editor has a static toolbar option. Not sure if this is something you want to consider or not. 

Links

- http://daviferreira.github.io/medium-editor/static-toolbar.html
- https://github.com/daviferreira/medium-editor/blob/master/demo/static-toolbar.html

**Comment by maxdumas** [comment]
@ethanresnick Where are you with the TinyMCE stuff?

**Comment by ethanresnick** [comment]
@maxdumas not very far, unfortunately. but i'll work on it a bit tonight and then post what i have. maybe someone else can take it from there? (cause i've really gotta switch to helping out with some design stuff, which we're getting a _huge_ bottleneck on, particularly with the new wiki and bd platforms)

**Comment by maxdumas** [comment]
Resolved by PR #100.
