### ISSUE TITLE
Adding Presenter must submit twitterId

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#51]
Right now, if a new presenter is created through the Add Event form (using the presenter partial), no `twitterId` is submitted with the presenter. I think twitterId should be autocomputed, based on the twitter username, and submitted.

**Comment by maxdumas** [comment]
Won't fix as of 671c2946dc70bdd2327c08cac88e47a02a137840. @ethanresnick decided that it was better to simply remove this field and handle it on the backend.
