### ISSUE TITLE
Presenter & Venue form Typeaheads/dropdowns

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#52]
In the presenter form partial, both skills and school should use typeaheads.

In the venue form, kind should be a dropdown based on the values allowed by the API.

**Comment by maxdumas** [comment]
@ethanresnick We need to do a similar thing with the Venue kinds that we are now doing with the skills. It should be easier to migrate the data since they aren't arrays. I can't finish this issue until that is done.

**Comment by ethanresnick** [comment]
I'm kinda loathe to make another resource type. Can we just get the typeahead list from a union of the kinds from `http://api.tnyu.org/v1.0/venues?fields=kind`. I think that's what we were going to do for schools...

**Comment by maxdumas** [comment]
Yeah sorry; we discussed this at the meeting on Sunday and that is what we are gonna go with.

**Comment by ethanresnick** [comment]
kewl

**Comment by ethanresnick** [comment]
Closing this and will replace with an updated version for the new architecture
