### ISSUE TITLE
Enable eboard meeting scheduling through Add Event form

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#57]
The only change this requires is that, in an exception to the `team.isMeta=false` rule for showing the possible teams hosting the event, an eboard meeting can be hosted by the [President & Chair](https://api.tnyu.org/v1.0/teams/54dd377891cb57536feb469f) team, so that should show up as an option in the Teams chicklet list.

**Comment by maxdumas** [comment]
I am going to double check this, but I am pretty sure that this is automatically accounted for now.

**Comment by ethanresnick** [comment]
@maxdumas Yes, this should be accounted for, but only because we're now allowing _any_ team to be linked, which is probably too lenient and might be less usable than the prior chicklets. If we want only `isMeta=false` teams + the President team to be able to be linked, this is an example of how we're going to either need to:

-
