### ISSUE TITLE
Check Builds

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#61]
Hey guys,

We can use Travis to check our build each time we commit it. If you don't know about [Travis](https://travis-ci.org) you can get to know it, and check it out. It's what I've used at work & for my personal projects. We can also use [CircleCI](https://circleci.com/).

It's going to be in the middle before the githook to the server is executed, and the user has committed to the master branch.

**Comment by ethanresnick** [comment]
Yes, yes, yes! Let's set Travis up for everything. Of course, we need to actually have some tests first for Travis to run :) But if you can even set up a test runner and test directory structure in each repo, so that we can actually write the tests later and then Travis will automatically run them, that would be awesome.

**Comment by AbhiAgarwal** [comment]
@ethanresnick Also checkout CircleCI. The cool thing about CircleCI is that they also give you ssh access to the box they use to test your code on for 20 minutes! So when we're testing you can get SSH access to test out the code yourself (etc)! 

I know we might not need this - but extra benefit!

**Comment by ethanresnick** [comment]
@AbhiAgarwal Yeah. Let's maybe do CircleCI for our private repos, since Travis can't do those, and Travis for our public ones, since that's free and unlimited (whereas CircleCI doesn't look like it can do much load before you have to start paying)?

**Comment by AbhiAgarwal** [comment]
@ethanresnick Well it has one container, which basically means that it's able to test one thing at one time. Every public repo has access to 3 extra, which is good for us. So private repos basically are bounded to 1. That doesn't seem too bad! I think they can do anything - it just matters on the number of containers & the fact that you can parallelize them

**Comment by ethanresnick** [comment]
@AbhiAgarwal Ok then, that sounds good. I didn't realize that public repos got extra containers. Let's go CircleCI all the way then!

**Comment by maxdumas** [comment]
This has been done for a while.
