### ISSUE TITLE
Session Management and Information

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#67]
For people on public computers

**Comment by maxdumas** [comment]
Renaming this to increase its scope. We need the intranet to automatically attempt sign-in, allow for manual sign-out, and to display relevant information depending on user permissions and how they are affecting the page they are currently viewing.

**Comment by ethanresnick** [comment]
Also, it needs to have a link to sign in if auto sign-in fails

**Comment by maxdumas** [comment]
This has been merged into `develop`. Awaiting merge into master.
