### ISSUE TITLE
Render Enum fields withs a select dropdown

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/intranet#69]
I.e. JSON like this from the API documentation, with the `oneOf` validation key:

```
{
  name: "positionLevel",
  friendlyName: "Position Level"
  validation: {
    required: true,
    oneOf: ["Full-Time", "Part-Time", "Contract", "Paid Internship"]
  },
  kind: {
    name: "String",
    isArray: false
  }
}
```

Should be rendered with a different partial that can put all the valid options into a dropdown, rather than the standard `<input type="text" />`.

This occurs for the `category` key in the `Job`, `Project`, and `Skill` models; the `kind` key for the `Venue` model; and the `positionLevel` key in the `Job` model.

**Comment by maxdumas** [comment]
This done.
