### ISSUE TITLE
Team page broken

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/intranet#70]
``http://admin.tnyu.org/#/r/teams/list/`` is broken. @maxdumas is aware that this page isn't working.

Just putting this here so it gets fixed at After Hours (22nd April).

**Comment by maxdumas** [comment]
@AbhiAgarwal I saw that you reverted a commit I made last night that fixed this? Were you able to tell from the diff what broke it?

**Comment by AbhiAgarwal** [comment]
@maxdumas I did not attempt yet - was in class haha. It broke all the listings, though. 

I'm not sure what happened, but when I woke up I got notifications that when you select a person the list of the person's details didn't show.

Namely ```about the api though: for some reason I can't see any information on any page?```
