### ISSUE TITLE
Enable HTML5 Mode Routing on Front-End

### ISSUE THREAD

**Issue by maxdumas** [TechAtNYU/intranet#72]
This will enable us to remove the hashes from our URLs, so that we can have URLs like `http://admin.tnyu.org/r/teams/list` instead of `http://admin.tnyu.org/#/r/teams/list`. It's for maximum sex appeal. :)

@AbhiAgarwal We'll need to set up our nginx deployment with a URL rewrite to support this. Google around; this gist seems promising: https://gist.github.com/cjus/b46a243ba610661a7efb

We'll need to set this up with our local dev environment too. It doesn't look like http-server, the module we're using to run this on development, supports this kind of advanced configuration, according to indexzero/http-server#80. However it looks like [superstatic](https://www.npmjs.com/package/superstatic) might be a good replacement for this that does support it. I'll look into this tonight.

**Comment by ethanresnick** [comment]
Aww yeah baby

**Comment by AbhiAgarwal** [comment]
@maxdumas We'll talk about this tonight. We're not using nginx anymore - we're running static file deployments. You can explain to me in more detail what this means, and we'll try figure out a solution.

**Comment by maxdumas** [comment]
For future readers: This issue was closed because our current host for the intranet, Rackspace Files, doesn't allow us to do the URL rewrite configuration necessary to make this work, and it was deemed not work it to pay for an actual server to get this to work.

**Comment by AbhiAgarwal** [comment]
@maxdumas Thanks for that!
