### ISSUE TITLE
Fix Angular TinyMCE Model Binding Errors

### ISSUE THREAD

**Issue by maxdumas** [TechAtNYU/intranet#95]
As far as I can tell, the tinyMCE directive is binding correctly to the model that it is assigned, but it is spitting out `TypeError: Cannot set property '<propertyName>' of undefined` every time an attempt is made to mutate the value bound in the tinyMCE directive.

**Comment by maxdumas** [comment]
As a further note, this only happens on the EDIT action. It is not present on the ADD action.

**Comment by ethanresnick** [comment]
P.S. Attributes are still getting stripped
